package com.league_enchant.magic;

import com.league_enchant.LeagueEnchantment;
import com.league_enchant.magic.spells.blood.AcupunctureSpell;
import com.league_enchant.magic.spells.blood.BloodNeedlesSpell;
import com.league_enchant.magic.spells.blood.BloodSlashSpell;
import com.league_enchant.magic.spells.blood.BloodStepSpell;
import com.league_enchant.magic.spells.blood.DevourSpell;
import com.league_enchant.magic.spells.blood.HeartstopSpell;
import com.league_enchant.magic.spells.blood.RaiseDeadSpell;
import com.league_enchant.magic.spells.blood.RayOfSiphoningSpell;
import com.league_enchant.magic.spells.blood.SacrificeSpell;
import com.league_enchant.magic.spells.blood.WitherSkullSpell;
import com.league_enchant.magic.spells.eldritch.AbyssalShroudSpell;
import com.league_enchant.magic.spells.eldritch.EldritchBlastSpell;
import com.league_enchant.magic.spells.eldritch.PlanarSightSpell;
import com.league_enchant.magic.spells.eldritch.PocketDimensionSpell;
import com.league_enchant.magic.spells.eldritch.SculkTentaclesSpell;
import com.league_enchant.magic.spells.eldritch.SonicBoomSpell;
import com.league_enchant.magic.spells.eldritch.TelekinesisSpell;
import com.league_enchant.magic.spells.evocation.ArrowVolleySpell;
import com.league_enchant.magic.spells.evocation.ChainCreeperSpell;
import com.league_enchant.magic.spells.evocation.FangStrikeSpell;
import com.league_enchant.magic.spells.evocation.FangSwirlSpell;
import com.league_enchant.magic.spells.evocation.FangWardSpell;
import com.league_enchant.magic.spells.evocation.FirecrackerSpell;
import com.league_enchant.magic.spells.evocation.GustSpell;
import com.league_enchant.magic.spells.evocation.InvisibilitySpell;
import com.league_enchant.magic.spells.evocation.LobCreeperSpell;
import com.league_enchant.magic.spells.evocation.ScapegoatSpell;
import com.league_enchant.magic.spells.evocation.ShieldSpell;
import com.league_enchant.magic.spells.evocation.SlowSpell;
import com.league_enchant.magic.spells.evocation.SpectralHammerSpell;
import com.league_enchant.magic.spells.evocation.SummonHorseSpell;
import com.league_enchant.magic.spells.evocation.SummonVexSpell;
import com.league_enchant.magic.spells.evocation.ThrowSpell;
import com.league_enchant.magic.spells.evocation.WololoSpell;
import com.league_enchant.magic.spells.FinalSparkSpell;
import com.league_enchant.magic.spells.fire.BlazeStormSpell;
import com.league_enchant.magic.spells.fire.BurningDashSpell;
import com.league_enchant.magic.spells.fire.FireArrowSpell;
import com.league_enchant.magic.spells.fire.FireboltSpell;
import com.league_enchant.magic.spells.fire.FireBreathSpell;
import com.league_enchant.magic.spells.fire.FlamingBarrageSpell;
import com.league_enchant.magic.spells.fire.FlamingStrikeSpell;
import com.league_enchant.magic.spells.fire.HeatSurgeSpell;
import com.league_enchant.magic.spells.fire.MagmaBombSpell;
import com.league_enchant.magic.spells.fire.MeteorSpell;
import com.league_enchant.magic.spells.fire.RaiseHellSpell;
import com.league_enchant.magic.spells.fire.ScorchSpell;
import com.league_enchant.magic.spells.fire.SoulfireRaySpell;
import com.league_enchant.magic.spells.fire.WallOfFireSpell;
import com.league_enchant.magic.spells.FireballSpell;
import com.league_enchant.magic.spells.HealSpell;
import com.league_enchant.magic.spells.holy.AngelWingsSpell;
import com.league_enchant.magic.spells.holy.BlessingOfLifeSpell;
import com.league_enchant.magic.spells.holy.CleanseSpell;
import com.league_enchant.magic.spells.holy.CloudOfRegenerationSpell;
import com.league_enchant.magic.spells.holy.DivineSmiteSpell;
import com.league_enchant.magic.spells.holy.FortifySpell;
import com.league_enchant.magic.spells.holy.GreaterHealSpell;
import com.league_enchant.magic.spells.holy.GuidingBoltSpell;
import com.league_enchant.magic.spells.holy.HasteSpell;
import com.league_enchant.magic.spells.holy.HealingCircleSpell;
import com.league_enchant.magic.spells.holy.SunbeamSpell;
import com.league_enchant.magic.spells.holy.WispSpell;
import com.league_enchant.magic.spells.ice.BlizzardSpell;
import com.league_enchant.magic.spells.ice.ConeOfColdSpell;
import com.league_enchant.magic.spells.ice.FrostbiteSpell;
import com.league_enchant.magic.spells.ice.FrostStepSpell;
import com.league_enchant.magic.spells.ice.FrostwaveSpell;
import com.league_enchant.magic.spells.ice.IceBlockSpell;
import com.league_enchant.magic.spells.ice.IceTombSpell;
import com.league_enchant.magic.spells.ice.IcicleSpell;
import com.league_enchant.magic.spells.ice.RayOfFrostSpell;
import com.league_enchant.magic.spells.ice.SnowballSpell;
import com.league_enchant.magic.spells.ice.SummonPolarBearSpell;
import com.league_enchant.magic.spells.IceSpikeSpell;
import com.league_enchant.magic.spells.lightning.AscensionSpell;
import com.league_enchant.magic.spells.lightning.BallLightningSpell;
import com.league_enchant.magic.spells.lightning.ChainLightningSpell;
import com.league_enchant.magic.spells.lightning.ChargeSpell;
import com.league_enchant.magic.spells.lightning.ElectrocuteSpell;
import com.league_enchant.magic.spells.lightning.LightningLanceSpell;
import com.league_enchant.magic.spells.lightning.ShockwaveSpell;
import com.league_enchant.magic.spells.lightning.ThunderStepSpell;
import com.league_enchant.magic.spells.lightning.ThunderstormSpell;
import com.league_enchant.magic.spells.lightning.VoltStrikeSpell;
import com.league_enchant.magic.spells.LightningBoltSpell;
import com.league_enchant.magic.spells.nature.AcidOrbSpell;
import com.league_enchant.magic.spells.nature.BlightSpell;
import com.league_enchant.magic.spells.nature.EarthquakeSpell;
import com.league_enchant.magic.spells.nature.FireflySwarmSpell;
import com.league_enchant.magic.spells.nature.GluttonySpell;
import com.league_enchant.magic.spells.nature.OakskinSpell;
import com.league_enchant.magic.spells.nature.PoisonArrowSpell;
import com.league_enchant.magic.spells.nature.PoisonBreathSpell;
import com.league_enchant.magic.spells.nature.PoisonSplashSpell;
import com.league_enchant.magic.spells.nature.RootSpell;
import com.league_enchant.magic.spells.nature.SpiderAspectSpell;
import com.league_enchant.magic.spells.nature.StompSpell;
import com.league_enchant.magic.spells.nature.TouchDigSpell;
import com.league_enchant.magic.spells.void_school.ArcaneShackleSpell;
import com.league_enchant.magic.spells.void_school.BlackHoleSpell;
import com.league_enchant.magic.spells.void_school.CounterspellSpell;
import com.league_enchant.magic.spells.void_school.DragonBreathSpell;
import com.league_enchant.magic.spells.void_school.EchoingStrikesSpell;
import com.league_enchant.magic.spells.void_school.EvasionSpell;
import com.league_enchant.magic.spells.void_school.GravityFissureSpell;
import com.league_enchant.magic.spells.void_school.MagicArrowSpell;
import com.league_enchant.magic.spells.void_school.MagicMissileSpell;
import com.league_enchant.magic.spells.void_school.PortalSpell;
import com.league_enchant.magic.spells.void_school.RecallSpell;
import com.league_enchant.magic.spells.void_school.ShadowSlashSpell;
import com.league_enchant.magic.spells.void_school.StarfallSpell;
import com.league_enchant.magic.spells.void_school.SummonEnderChestSpell;
import com.league_enchant.magic.spells.void_school.SummonSwordsSpell;
import com.league_enchant.magic.spells.void_school.TeleportSpell;

import java.util.Collection;
import java.util.HashMap;
import java.util.Map;

public class SpellRegistry {
    private static final Map<String, AbstractSpell> SPELLS = new HashMap<>();

    public static final AbstractSpell ABYSSAL_SHROUD = register(new AbyssalShroudSpell());
    public static final AbstractSpell ACID_ORB = register(new AcidOrbSpell());
    public static final AbstractSpell ACUPUNCTURE = register(new AcupunctureSpell());
    public static final AbstractSpell ANGEL_WINGS = register(new AngelWingsSpell());
    public static final AbstractSpell ARCANE_SHACKLE = register(new ArcaneShackleSpell());
    public static final AbstractSpell ARROW_VOLLEY = register(new ArrowVolleySpell());
    public static final AbstractSpell ASCENSION = register(new AscensionSpell());
    public static final AbstractSpell BALL_LIGHTNING = register(new BallLightningSpell());
    public static final AbstractSpell BLACK_HOLE = register(new BlackHoleSpell());
    public static final AbstractSpell BLAZE_STORM = register(new BlazeStormSpell());
    public static final AbstractSpell BLESSING_OF_LIFE = register(new BlessingOfLifeSpell());
    public static final AbstractSpell BLIGHT = register(new BlightSpell());
    public static final AbstractSpell BLIZZARD = register(new BlizzardSpell());
    public static final AbstractSpell BLOOD_NEEDLES = register(new BloodNeedlesSpell());
    public static final AbstractSpell BLOOD_SLASH = register(new BloodSlashSpell());
    public static final AbstractSpell BLOOD_STEP = register(new BloodStepSpell());
    public static final AbstractSpell BURNING_DASH = register(new BurningDashSpell());
    public static final AbstractSpell CHAIN_CREEPER = register(new ChainCreeperSpell());
    public static final AbstractSpell CHAIN_LIGHTNING = register(new ChainLightningSpell());
    public static final AbstractSpell CHARGE = register(new ChargeSpell());
    public static final AbstractSpell CLEANSE = register(new CleanseSpell());
    public static final AbstractSpell CLOUD_OF_REGENERATION = register(new CloudOfRegenerationSpell());
    public static final AbstractSpell CONE_OF_COLD = register(new ConeOfColdSpell());
    public static final AbstractSpell COUNTERSPELL = register(new CounterspellSpell());
    public static final AbstractSpell DEVOUR = register(new DevourSpell());
    public static final AbstractSpell DIVINE_SMITE = register(new DivineSmiteSpell());
    public static final AbstractSpell DRAGON_BREATH = register(new DragonBreathSpell());
    public static final AbstractSpell EARTHQUAKE = register(new EarthquakeSpell());
    public static final AbstractSpell ECHOING_STRIKES = register(new EchoingStrikesSpell());
    public static final AbstractSpell ELDRITCH_BLAST = register(new EldritchBlastSpell());
    public static final AbstractSpell ELECTROCUTE = register(new ElectrocuteSpell());
    public static final AbstractSpell EVASION = register(new EvasionSpell());
    public static final AbstractSpell FANG_STRIKE = register(new FangStrikeSpell());
    public static final AbstractSpell FANG_SWIRL = register(new FangSwirlSpell());
    public static final AbstractSpell FANG_WARD = register(new FangWardSpell());
    public static final AbstractSpell FINAL_SPARK = register(new FinalSparkSpell());
    public static final AbstractSpell FIRE_ARROW = register(new FireArrowSpell());
    public static final AbstractSpell FIRE_BREATH = register(new FireBreathSpell());
    public static final AbstractSpell FIREBALL = register(new FireballSpell());
    public static final AbstractSpell FIREBOLT = register(new FireboltSpell());
    public static final AbstractSpell FIRECRACKER = register(new FirecrackerSpell());
    public static final AbstractSpell FIREFLY_SWARM = register(new FireflySwarmSpell());
    public static final AbstractSpell FLAMING_BARRAGE = register(new FlamingBarrageSpell());
    public static final AbstractSpell FLAMING_STRIKE = register(new FlamingStrikeSpell());
    public static final AbstractSpell FORTIFY = register(new FortifySpell());
    public static final AbstractSpell FROST_STEP = register(new FrostStepSpell());
    public static final AbstractSpell FROSTBITE = register(new FrostbiteSpell());
    public static final AbstractSpell FROSTWAVE = register(new FrostwaveSpell());
    public static final AbstractSpell GLUTTONY = register(new GluttonySpell());
    public static final AbstractSpell GRAVITY_FISSURE = register(new GravityFissureSpell());
    public static final AbstractSpell GREATER_HEAL = register(new GreaterHealSpell());
    public static final AbstractSpell GUIDING_BOLT = register(new GuidingBoltSpell());
    public static final AbstractSpell GUST = register(new GustSpell());
    public static final AbstractSpell HASTE = register(new HasteSpell());
    public static final AbstractSpell HEAL = register(new HealSpell());
    public static final AbstractSpell HEALING_CIRCLE = register(new HealingCircleSpell());
    public static final AbstractSpell HEARTSTOP = register(new HeartstopSpell());
    public static final AbstractSpell HEAT_SURGE = register(new HeatSurgeSpell());
    public static final AbstractSpell ICE_BLOCK = register(new IceBlockSpell());
    public static final AbstractSpell ICE_SPIKE = register(new IceSpikeSpell());
    public static final AbstractSpell ICE_TOMB = register(new IceTombSpell());
    public static final AbstractSpell ICICLE = register(new IcicleSpell());
    public static final AbstractSpell INVISIBILITY = register(new InvisibilitySpell());
    public static final AbstractSpell LIGHTNING_BOLT = register(new LightningBoltSpell());
    public static final AbstractSpell LIGHTNING_LANCE = register(new LightningLanceSpell());
    public static final AbstractSpell LOB_CREEPER = register(new LobCreeperSpell());
    public static final AbstractSpell MAGIC_ARROW = register(new MagicArrowSpell());
    public static final AbstractSpell MAGIC_MISSILE = register(new MagicMissileSpell());
    public static final AbstractSpell MAGMA_BOMB = register(new MagmaBombSpell());
    public static final AbstractSpell METEOR = register(new MeteorSpell());
    public static final AbstractSpell OAKSKIN = register(new OakskinSpell());
    public static final AbstractSpell PLANAR_SIGHT = register(new PlanarSightSpell());
    public static final AbstractSpell POCKET_DIMENSION = register(new PocketDimensionSpell());
    public static final AbstractSpell POISON_ARROW = register(new PoisonArrowSpell());
    public static final AbstractSpell POISON_BREATH = register(new PoisonBreathSpell());
    public static final AbstractSpell POISON_SPLASH = register(new PoisonSplashSpell());
    public static final AbstractSpell PORTAL = register(new PortalSpell());
    public static final AbstractSpell RAISE_DEAD = register(new RaiseDeadSpell());
    public static final AbstractSpell RAISE_HELL = register(new RaiseHellSpell());
    public static final AbstractSpell RAY_OF_FROST = register(new RayOfFrostSpell());
    public static final AbstractSpell RAY_OF_SIPHONING = register(new RayOfSiphoningSpell());
    public static final AbstractSpell RECALL = register(new RecallSpell());
    public static final AbstractSpell ROOT = register(new RootSpell());
    public static final AbstractSpell SACRIFICE = register(new SacrificeSpell());
    public static final AbstractSpell SCAPEGOAT = register(new ScapegoatSpell());
    public static final AbstractSpell SCORCH = register(new ScorchSpell());
    public static final AbstractSpell SCULK_TENTACLES = register(new SculkTentaclesSpell());
    public static final AbstractSpell SHADOW_SLASH = register(new ShadowSlashSpell());
    public static final AbstractSpell SHIELD = register(new ShieldSpell());
    public static final AbstractSpell SHOCKWAVE = register(new ShockwaveSpell());
    public static final AbstractSpell SLOW = register(new SlowSpell());
    public static final AbstractSpell SNOWBALL = register(new SnowballSpell());
    public static final AbstractSpell SONIC_BOOM = register(new SonicBoomSpell());
    public static final AbstractSpell SOULFIRE_RAY = register(new SoulfireRaySpell());
    public static final AbstractSpell SPECTRAL_HAMMER = register(new SpectralHammerSpell());
    public static final AbstractSpell SPIDER_ASPECT = register(new SpiderAspectSpell());
    public static final AbstractSpell STARFALL = register(new StarfallSpell());
    public static final AbstractSpell STOMP = register(new StompSpell());
    public static final AbstractSpell SUMMON_ENDER_CHEST = register(new SummonEnderChestSpell());
    public static final AbstractSpell SUMMON_HORSE = register(new SummonHorseSpell());
    public static final AbstractSpell SUMMON_POLAR_BEAR = register(new SummonPolarBearSpell());
    public static final AbstractSpell SUMMON_SWORDS = register(new SummonSwordsSpell());
    public static final AbstractSpell SUMMON_VEX = register(new SummonVexSpell());
    public static final AbstractSpell SUNBEAM = register(new SunbeamSpell());
    public static final AbstractSpell TELEKINESIS = register(new TelekinesisSpell());
    public static final AbstractSpell TELEPORT = register(new TeleportSpell());
    public static final AbstractSpell THROW = register(new ThrowSpell());
    public static final AbstractSpell THUNDER_STEP = register(new ThunderStepSpell());
    public static final AbstractSpell THUNDERSTORM = register(new ThunderstormSpell());
    public static final AbstractSpell TOUCH_DIG = register(new TouchDigSpell());
    public static final AbstractSpell VOLT_STRIKE = register(new VoltStrikeSpell());
    public static final AbstractSpell WALL_OF_FIRE = register(new WallOfFireSpell());
    public static final AbstractSpell WISP = register(new WispSpell());
    public static final AbstractSpell WITHER_SKULL = register(new WitherSkullSpell());
    public static final AbstractSpell WOLOLO = register(new WololoSpell());

    private static <T extends AbstractSpell> T register(T spell) {
        SPELLS.put(spell.getSpellId(), spell);
        return spell;
    }

    public static AbstractSpell getSpell(String spellId) {
        return SPELLS.get(spellId);
    }

    public static Collection<AbstractSpell> getAllSpells() {
        return SPELLS.values();
    }

    public static void registerSpells() {
        LeagueEnchantment.LOGGER.info("Registering " + SPELLS.size() + " Magic Spells for " + LeagueEnchantment.MOD_ID);
    }
}
