package com.league_enchant.registry;

import com.league_enchant.LeagueEnchantment;
import com.league_enchant.magic.ScrollItem;
import com.league_enchant.magic.SpellbookItem;
import net.fabricmc.fabric.api.itemgroup.v1.ItemGroupEvents;
import net.minecraft.item.Item;
import net.minecraft.item.ItemGroups;
import net.minecraft.registry.Registries;
import net.minecraft.registry.Registry;
import net.minecraft.util.Identifier;
import net.minecraft.util.Rarity;

public class ModItems {
    // 16 Exact Iron's Spells Spellbooks
    public static final Item WIMPY_SPELL_BOOK = register("wimpy_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.COMMON)));
    public static final Item COPPER_SPELL_BOOK = register("copper_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.COMMON)));
    public static final Item IRON_SPELL_BOOK = register("iron_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.UNCOMMON)));
    public static final Item GOLD_SPELL_BOOK = register("gold_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.UNCOMMON)));
    public static final Item DIAMOND_SPELL_BOOK = register("diamond_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.RARE)));
    public static final Item NETHERITE_SPELL_BOOK = register("netherite_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).fireproof().rarity(Rarity.EPIC)));
    public static final Item LEGENDARY_SPELL_BOOK = register("legendary_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.EPIC)));
    public static final Item ROTTEN_SPELL_BOOK = register("rotten_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.UNCOMMON)));
    public static final Item BLAZE_SPELL_BOOK = register("blaze_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.RARE)));
    public static final Item DRAGONSKIN_SPELL_BOOK = register("dragonskin_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.EPIC)));
    public static final Item DRUIDIC_SPELL_BOOK = register("druidic_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.RARE)));
    public static final Item VILLAGER_SPELL_BOOK = register("villager_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.UNCOMMON)));
    public static final Item ICE_SPELL_BOOK = register("ice_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.RARE)));
    public static final Item EVOKER_SPELL_BOOK = register("evoker_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.RARE)));
    public static final Item NECRONOMICON_SPELL_BOOK = register("necronomicon_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.EPIC)));
    public static final Item CURSED_DOLL_SPELLBOOK = register("cursed_doll_spell_book", new SpellbookItem(new Item.Settings().maxCount(1).fireproof().rarity(Rarity.UNCOMMON)));

    public static final Item SPELLBOOK = register("spellbook", new SpellbookItem(new Item.Settings().maxCount(1).rarity(Rarity.EPIC)));
    public static final Item SCROLL = register("scroll", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));

    // All Spell Scrolls
    public static final Item SCROLL_ABYSSAL_SHROUD = register("scroll_abyssal_shroud", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ACID_ORB = register("scroll_acid_orb", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ACUPUNCTURE = register("scroll_acupuncture", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ANGEL_WINGS = register("scroll_angel_wings", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ARCANE_SHACKLE = register("scroll_arcane_shackle", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ARROW_VOLLEY = register("scroll_arrow_volley", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ASCENSION = register("scroll_ascension", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BALL_LIGHTNING = register("scroll_ball_lightning", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLACK_HOLE = register("scroll_black_hole", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLAZE_STORM = register("scroll_blaze_storm", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLESSING_OF_LIFE = register("scroll_blessing_of_life", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLIGHT = register("scroll_blight", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLIZZARD = register("scroll_blizzard", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLOOD_NEEDLES = register("scroll_blood_needles", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLOOD_SLASH = register("scroll_blood_slash", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BLOOD_STEP = register("scroll_blood_step", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_BURNING_DASH = register("scroll_burning_dash", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_CHAIN_CREEPER = register("scroll_chain_creeper", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_CHAIN_LIGHTNING = register("scroll_chain_lightning", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_CHARGE = register("scroll_charge", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_CLEANSE = register("scroll_cleanse", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_CLOUD_OF_REGENERATION = register("scroll_cloud_of_regeneration", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_CONE_OF_COLD = register("scroll_cone_of_cold", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_COUNTERSPELL = register("scroll_counterspell", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_DEVOUR = register("scroll_devour", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_DIVINE_SMITE = register("scroll_divine_smite", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_DRAGON_BREATH = register("scroll_dragon_breath", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_EARTHQUAKE = register("scroll_earthquake", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ECHOING_STRIKES = register("scroll_echoing_strikes", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ELDRITCH_BLAST = register("scroll_eldritch_blast", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ELECTROCUTE = register("scroll_electrocute", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_EVASION = register("scroll_evasion", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FANG_STRIKE = register("scroll_fang_strike", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FANG_SWIRL = register("scroll_fang_swirl", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FANG_WARD = register("scroll_fang_ward", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FINAL_SPARK = register("scroll_final_spark", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FIRE_ARROW = register("scroll_fire_arrow", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FIRE_BREATH = register("scroll_fire_breath", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FIREBALL = register("scroll_fireball", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FIREBOLT = register("scroll_firebolt", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FIRECRACKER = register("scroll_firecracker", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FIREFLY_SWARM = register("scroll_firefly_swarm", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FLAMING_BARRAGE = register("scroll_flaming_barrage", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FLAMING_STRIKE = register("scroll_flaming_strike", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FORTIFY = register("scroll_fortify", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FROST_STEP = register("scroll_frost_step", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FROSTBITE = register("scroll_frostbite", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_FROSTWAVE = register("scroll_frostwave", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_GLUTTONY = register("scroll_gluttony", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_GRAVITY_FISSURE = register("scroll_gravity_fissure", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_GREATER_HEAL = register("scroll_greater_heal", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_GUIDING_BOLT = register("scroll_guiding_bolt", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_GUST = register("scroll_gust", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_HASTE = register("scroll_haste", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_HEAL = register("scroll_heal", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_HEALING_CIRCLE = register("scroll_healing_circle", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_HEARTSTOP = register("scroll_heartstop", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_HEAT_SURGE = register("scroll_heat_surge", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ICE_BLOCK = register("scroll_ice_block", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ICE_SPIKE = register("scroll_ice_spike", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ICE_TOMB = register("scroll_ice_tomb", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ICICLE = register("scroll_icicle", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_INVISIBILITY = register("scroll_invisibility", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_LIGHTNING_BOLT = register("scroll_lightning_bolt", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_LIGHTNING_LANCE = register("scroll_lightning_lance", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_LOB_CREEPER = register("scroll_lob_creeper", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_MAGIC_ARROW = register("scroll_magic_arrow", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_MAGIC_MISSILE = register("scroll_magic_missile", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_MAGMA_BOMB = register("scroll_magma_bomb", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_METEOR = register("scroll_meteor", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_OAKSKIN = register("scroll_oakskin", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_PLANAR_SIGHT = register("scroll_planar_sight", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_POCKET_DIMENSION = register("scroll_pocket_dimension", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_POISON_ARROW = register("scroll_poison_arrow", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_POISON_BREATH = register("scroll_poison_breath", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_POISON_SPLASH = register("scroll_poison_splash", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_PORTAL = register("scroll_portal", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_RAISE_DEAD = register("scroll_raise_dead", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_RAISE_HELL = register("scroll_raise_hell", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_RAY_OF_FROST = register("scroll_ray_of_frost", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_RAY_OF_SIPHONING = register("scroll_ray_of_siphoning", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_RECALL = register("scroll_recall", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_ROOT = register("scroll_root", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SACRIFICE = register("scroll_sacrifice", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SCAPEGOAT = register("scroll_scapegoat", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SCORCH = register("scroll_scorch", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SCULK_TENTACLES = register("scroll_sculk_tentacles", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SHADOW_SLASH = register("scroll_shadow_slash", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SHIELD = register("scroll_shield", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SHOCKWAVE = register("scroll_shockwave", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SLOW = register("scroll_slow", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SNOWBALL = register("scroll_snowball", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SONIC_BOOM = register("scroll_sonic_boom", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SOULFIRE_RAY = register("scroll_soulfire_ray", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SPECTRAL_HAMMER = register("scroll_spectral_hammer", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SPIDER_ASPECT = register("scroll_spider_aspect", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_STARFALL = register("scroll_starfall", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_STOMP = register("scroll_stomp", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SUMMON_ENDER_CHEST = register("scroll_summon_ender_chest", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SUMMON_HORSE = register("scroll_summon_horse", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SUMMON_POLAR_BEAR = register("scroll_summon_polar_bear", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SUMMON_SWORDS = register("scroll_summon_swords", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SUMMON_VEX = register("scroll_summon_vex", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_SUNBEAM = register("scroll_sunbeam", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_TELEKINESIS = register("scroll_telekinesis", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_TELEPORT = register("scroll_teleport", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_THROW = register("scroll_throw", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_THUNDER_STEP = register("scroll_thunder_step", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_THUNDERSTORM = register("scroll_thunderstorm", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_TOUCH_DIG = register("scroll_touch_dig", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_VOLT_STRIKE = register("scroll_volt_strike", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_WALL_OF_FIRE = register("scroll_wall_of_fire", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_WISP = register("scroll_wisp", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_WITHER_SKULL = register("scroll_wither_skull", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));
    public static final Item SCROLL_WOLOLO = register("scroll_wololo", new ScrollItem(new Item.Settings().maxCount(16).rarity(Rarity.RARE)));

    private static Item register(String name, Item item) {
        return Registry.register(
            Registries.ITEM,
            new Identifier(LeagueEnchantment.MOD_ID, name),
            item
        );
    }

    public static void registerModItems() {
        LeagueEnchantment.LOGGER.info("Registering Mod Items for " + LeagueEnchantment.MOD_ID);
        ItemGroupEvents.modifyEntriesEvent(ItemGroups.COMBAT).register(content -> {
            content.add(WIMPY_SPELL_BOOK);
            content.add(COPPER_SPELL_BOOK);
            content.add(IRON_SPELL_BOOK);
            content.add(GOLD_SPELL_BOOK);
            content.add(DIAMOND_SPELL_BOOK);
            content.add(NETHERITE_SPELL_BOOK);
            content.add(LEGENDARY_SPELL_BOOK);
            content.add(ROTTEN_SPELL_BOOK);
            content.add(BLAZE_SPELL_BOOK);
            content.add(DRAGONSKIN_SPELL_BOOK);
            content.add(DRUIDIC_SPELL_BOOK);
            content.add(VILLAGER_SPELL_BOOK);
            content.add(ICE_SPELL_BOOK);
            content.add(EVOKER_SPELL_BOOK);
            content.add(NECRONOMICON_SPELL_BOOK);
            content.add(CURSED_DOLL_SPELLBOOK);
            content.add(SPELLBOOK);
            content.add(SCROLL);
            content.add(SCROLL_ABYSSAL_SHROUD);
            content.add(SCROLL_ACID_ORB);
            content.add(SCROLL_ACUPUNCTURE);
            content.add(SCROLL_ANGEL_WINGS);
            content.add(SCROLL_ARCANE_SHACKLE);
            content.add(SCROLL_ARROW_VOLLEY);
            content.add(SCROLL_ASCENSION);
            content.add(SCROLL_BALL_LIGHTNING);
            content.add(SCROLL_BLACK_HOLE);
            content.add(SCROLL_BLAZE_STORM);
            content.add(SCROLL_BLESSING_OF_LIFE);
            content.add(SCROLL_BLIGHT);
            content.add(SCROLL_BLIZZARD);
            content.add(SCROLL_BLOOD_NEEDLES);
            content.add(SCROLL_BLOOD_SLASH);
            content.add(SCROLL_BLOOD_STEP);
            content.add(SCROLL_BURNING_DASH);
            content.add(SCROLL_CHAIN_CREEPER);
            content.add(SCROLL_CHAIN_LIGHTNING);
            content.add(SCROLL_CHARGE);
            content.add(SCROLL_CLEANSE);
            content.add(SCROLL_CLOUD_OF_REGENERATION);
            content.add(SCROLL_CONE_OF_COLD);
            content.add(SCROLL_COUNTERSPELL);
            content.add(SCROLL_DEVOUR);
            content.add(SCROLL_DIVINE_SMITE);
            content.add(SCROLL_DRAGON_BREATH);
            content.add(SCROLL_EARTHQUAKE);
            content.add(SCROLL_ECHOING_STRIKES);
            content.add(SCROLL_ELDRITCH_BLAST);
            content.add(SCROLL_ELECTROCUTE);
            content.add(SCROLL_EVASION);
            content.add(SCROLL_FANG_STRIKE);
            content.add(SCROLL_FANG_SWIRL);
            content.add(SCROLL_FANG_WARD);
            content.add(SCROLL_FINAL_SPARK);
            content.add(SCROLL_FIRE_ARROW);
            content.add(SCROLL_FIRE_BREATH);
            content.add(SCROLL_FIREBALL);
            content.add(SCROLL_FIREBOLT);
            content.add(SCROLL_FIRECRACKER);
            content.add(SCROLL_FIREFLY_SWARM);
            content.add(SCROLL_FLAMING_BARRAGE);
            content.add(SCROLL_FLAMING_STRIKE);
            content.add(SCROLL_FORTIFY);
            content.add(SCROLL_FROST_STEP);
            content.add(SCROLL_FROSTBITE);
            content.add(SCROLL_FROSTWAVE);
            content.add(SCROLL_GLUTTONY);
            content.add(SCROLL_GRAVITY_FISSURE);
            content.add(SCROLL_GREATER_HEAL);
            content.add(SCROLL_GUIDING_BOLT);
            content.add(SCROLL_GUST);
            content.add(SCROLL_HASTE);
            content.add(SCROLL_HEAL);
            content.add(SCROLL_HEALING_CIRCLE);
            content.add(SCROLL_HEARTSTOP);
            content.add(SCROLL_HEAT_SURGE);
            content.add(SCROLL_ICE_BLOCK);
            content.add(SCROLL_ICE_SPIKE);
            content.add(SCROLL_ICE_TOMB);
            content.add(SCROLL_ICICLE);
            content.add(SCROLL_INVISIBILITY);
            content.add(SCROLL_LIGHTNING_BOLT);
            content.add(SCROLL_LIGHTNING_LANCE);
            content.add(SCROLL_LOB_CREEPER);
            content.add(SCROLL_MAGIC_ARROW);
            content.add(SCROLL_MAGIC_MISSILE);
            content.add(SCROLL_MAGMA_BOMB);
            content.add(SCROLL_METEOR);
            content.add(SCROLL_OAKSKIN);
            content.add(SCROLL_PLANAR_SIGHT);
            content.add(SCROLL_POCKET_DIMENSION);
            content.add(SCROLL_POISON_ARROW);
            content.add(SCROLL_POISON_BREATH);
            content.add(SCROLL_POISON_SPLASH);
            content.add(SCROLL_PORTAL);
            content.add(SCROLL_RAISE_DEAD);
            content.add(SCROLL_RAISE_HELL);
            content.add(SCROLL_RAY_OF_FROST);
            content.add(SCROLL_RAY_OF_SIPHONING);
            content.add(SCROLL_RECALL);
            content.add(SCROLL_ROOT);
            content.add(SCROLL_SACRIFICE);
            content.add(SCROLL_SCAPEGOAT);
            content.add(SCROLL_SCORCH);
            content.add(SCROLL_SCULK_TENTACLES);
            content.add(SCROLL_SHADOW_SLASH);
            content.add(SCROLL_SHIELD);
            content.add(SCROLL_SHOCKWAVE);
            content.add(SCROLL_SLOW);
            content.add(SCROLL_SNOWBALL);
            content.add(SCROLL_SONIC_BOOM);
            content.add(SCROLL_SOULFIRE_RAY);
            content.add(SCROLL_SPECTRAL_HAMMER);
            content.add(SCROLL_SPIDER_ASPECT);
            content.add(SCROLL_STARFALL);
            content.add(SCROLL_STOMP);
            content.add(SCROLL_SUMMON_ENDER_CHEST);
            content.add(SCROLL_SUMMON_HORSE);
            content.add(SCROLL_SUMMON_POLAR_BEAR);
            content.add(SCROLL_SUMMON_SWORDS);
            content.add(SCROLL_SUMMON_VEX);
            content.add(SCROLL_SUNBEAM);
            content.add(SCROLL_TELEKINESIS);
            content.add(SCROLL_TELEPORT);
            content.add(SCROLL_THROW);
            content.add(SCROLL_THUNDER_STEP);
            content.add(SCROLL_THUNDERSTORM);
            content.add(SCROLL_TOUCH_DIG);
            content.add(SCROLL_VOLT_STRIKE);
            content.add(SCROLL_WALL_OF_FIRE);
            content.add(SCROLL_WISP);
            content.add(SCROLL_WITHER_SKULL);
            content.add(SCROLL_WOLOLO);
        });
    }
}
